import { StyleSheet } from "react-native";

import { colors, radius, spacing, typography } from "../../theme";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  container: { padding: spacing.xl, gap: spacing.lg, paddingBottom: 44 },
  tabs: { flexDirection: "row", backgroundColor: colors.surfaceMuted, borderRadius: radius.lg, padding: 4, gap: 4 },
  tab: { flex: 1, minHeight: 44, borderRadius: radius.md, alignItems: "center", justifyContent: "center", paddingHorizontal: spacing.xs },
  activeTab: { backgroundColor: colors.surface, shadowColor: colors.navy, shadowOpacity: 0.08, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  tabText: { fontSize: 13, fontWeight: "700", color: colors.textMuted, textAlign: "center" },
  activeTabText: { color: colors.primary },
  placeholder: { alignItems: "center", paddingVertical: spacing.xxl, gap: spacing.sm },
  placeholderIcon: { width: 62, height: 62, borderRadius: 31, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center", marginBottom: spacing.xs },
  placeholderTitle: { ...typography.section, color: colors.navy, textAlign: "center", marginTop: spacing.xs },
  placeholderMessage: { ...typography.body, color: colors.textMuted, textAlign: "center", lineHeight: 21, maxWidth: 330 },
  note: { flexDirection: "row", gap: spacing.sm, backgroundColor: colors.infoBg, borderRadius: radius.lg, padding: spacing.md },
  noteText: { flex: 1, color: colors.infoFg, fontSize: 13, lineHeight: 18 },
  suggestions: { gap: spacing.md },
  manualAnnotationCallout: { gap: spacing.md },
  manualAnnotationIcon: { width: 48, height: 48, borderRadius: radius.lg, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" },
  manualAnnotationTitle: { ...typography.section, color: colors.navy },
  targetedHelp: { flexDirection: "row", alignItems: "flex-start", gap: spacing.sm, backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: "#93c5fd", borderRadius: radius.lg, padding: spacing.md },
  targetedHelpTitle: { color: colors.navy, fontWeight: "800" },
  targetedHelpText: { color: colors.textSecondary, fontSize: 13, lineHeight: 18 },
  targetedDetection: { borderWidth: 2, borderColor: colors.primary, borderRadius: radius.xl, padding: 2 },
  sectionHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  sectionTitle: { ...typography.section, color: colors.navy },
  sectionSubtitle: { color: colors.textMuted, fontSize: 13, marginTop: 3 },
  loading: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing.sm, paddingVertical: spacing.lg },
  loadingText: { color: colors.textMuted, fontWeight: "600" },
  scanList: { gap: spacing.sm, paddingVertical: 2 },
  filterList: { gap: spacing.sm, paddingVertical: 2 },
  searchInput: { minHeight: 48, borderWidth: 1, borderColor: colors.borderStrong, borderRadius: radius.lg, paddingHorizontal: spacing.md, color: colors.textPrimary, backgroundColor: colors.surface },
  filterCaption: { color: colors.textMuted, fontSize: 11, fontWeight: "800", letterSpacing: 0.8, marginBottom: spacing.xs, marginTop: spacing.md },
  sortOptions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  sortChip: { flexGrow: 1, minWidth: 88 },
  filterChip: { minHeight: 38, paddingHorizontal: spacing.md, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" },
  selectedFilterChip: { backgroundColor: colors.primary, borderColor: colors.primary },
  filterText: { color: colors.textSecondary, fontWeight: "700", fontSize: 13 },
  selectedFilterText: { color: colors.primaryText },
  scanChip: { minWidth: 126, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, padding: spacing.md, gap: 3 },
  selectedScanChip: { backgroundColor: colors.primary, borderColor: colors.primary },
  scanChipTitle: { fontWeight: "800", color: colors.navy },
  scanChipMeta: { color: colors.textMuted, fontSize: 13 },
  selectedScanText: { color: colors.primaryText },
  errorBox: { gap: spacing.sm, backgroundColor: colors.dangerBg, padding: spacing.md, borderRadius: radius.lg },
  errorText: { color: colors.danger, textAlign: "center", fontWeight: "600" },
  detectionTop: { flexDirection: "row", alignItems: "center", gap: spacing.md },
  contributionHeader: { flexDirection: "row", alignItems: "center", gap: spacing.md },
  contributionProduct: { flexShrink: 1, color: colors.navy, fontSize: 18, lineHeight: 23, fontWeight: "900" },
  contributionAction: { flexShrink: 1, color: colors.textSecondary, fontSize: 13, lineHeight: 18, fontWeight: "700" },
  contributionGroup: { gap: spacing.md },
  groupHeading: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between", gap: spacing.md, paddingHorizontal: spacing.xs, paddingTop: spacing.sm },
  groupTitle: { flex: 1, color: colors.navy, fontSize: 19, lineHeight: 24, fontWeight: "900" },
  groupCount: { color: colors.textMuted, fontSize: 13, fontWeight: "700" },
  detectionIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" },
  removeIcon: { backgroundColor: colors.dangerBg },
  detectionCopy: { flex: 1, gap: 3 },
  detectionLabel: { fontSize: 17, fontWeight: "800", color: colors.navy },
  detectionMeta: { color: colors.textMuted, fontSize: 13 },
  pendingRow: { marginTop: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.sm, backgroundColor: colors.warningBg, borderRadius: radius.lg, padding: spacing.sm },
  pendingText: { flex: 1, color: colors.warningFg, fontSize: 13, fontWeight: "600" },
  falsePositiveRow: { marginTop: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.sm, backgroundColor: colors.dangerBg, borderRadius: radius.lg, padding: spacing.sm },
  falsePositiveText: { flex: 1, color: colors.danger, fontSize: 13, fontWeight: "700" },
  confirmedRow: { marginTop: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.sm, backgroundColor: colors.successBg, borderRadius: radius.lg, padding: spacing.sm },
  confirmedText: { flex: 1, color: colors.successFg, fontSize: 13, fontWeight: "700" },
  detectionActions: { marginTop: spacing.md, paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.border, flexDirection: "row", gap: spacing.sm },
  detectionActionsSecondary: { marginTop: spacing.sm, flexDirection: "row", gap: spacing.sm },
  detectionAction: { flex: 1 },
  removeAction: { marginTop: spacing.sm },
  confirmAction: { marginTop: spacing.sm },
  labelDetail: { marginTop: spacing.md, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  detailCaption: { color: colors.textMuted, fontSize: 13 },
  detailValue: { flex: 1, color: colors.navy, fontWeight: "800", textAlign: "right" },
  changeStory: { marginTop: spacing.md, padding: spacing.md, gap: spacing.sm, backgroundColor: colors.surfaceMuted, borderRadius: radius.lg, alignItems: "flex-start" },
  storyStep: { gap: 3, width: "100%" },
  storyValue: { color: colors.navy, fontWeight: "800", fontSize: 14, lineHeight: 19 },
  usedModelBox: { marginTop: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.sm, backgroundColor: colors.successBg, borderRadius: radius.lg, padding: spacing.md },
  usedModelTitle: { color: colors.successFg, fontSize: 13, fontWeight: "800" },
  usedModelMeta: { color: colors.successFg, fontSize: 12, lineHeight: 17 },
  lifecycleStateRow: { marginTop: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.sm, padding: spacing.sm, borderRadius: radius.lg, backgroundColor: colors.surfaceMuted },
  lifecycleStateText: { flex: 1, color: colors.textSecondary, fontSize: 12, lineHeight: 17, fontWeight: "600" },
  readOnlyText: { marginTop: spacing.sm, color: colors.textMuted, fontSize: 13, fontWeight: "600", textAlign: "center" },
  moderationDivider: { marginTop: spacing.xl, paddingTop: spacing.xl, borderTopWidth: 2, borderTopColor: colors.border, flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: spacing.md },
  queueTitleRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: spacing.sm },
  moderationHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md, marginBottom: spacing.md },
  moderationImage: { width: "100%", height: 300, backgroundColor: colors.surfaceMuted, borderRadius: radius.lg },
  moderationAnnotations: { marginTop: spacing.md, gap: spacing.sm },
  moderationAnnotation: { backgroundColor: colors.surfaceMuted, borderRadius: radius.lg, padding: spacing.md, gap: 5 },
  annotationTitleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: spacing.sm },
  annotationTitle: { color: colors.navy, fontWeight: "800", fontSize: 15 },
  annotationId: { color: colors.textMuted, fontSize: 12, fontWeight: "700" },
  annotationDetail: { color: colors.textMuted, fontSize: 13, lineHeight: 18 },
  annotationValue: { color: colors.textSecondary, fontWeight: "700" },
  detailsToggle: { minHeight: 44, alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: spacing.xs, marginTop: spacing.xs },
  detailsToggleText: { color: colors.primary, fontSize: 13, fontWeight: "800" },
  coordinateDetails: { gap: spacing.xs, paddingTop: spacing.xs, borderTopWidth: 1, borderTopColor: colors.border },
  moderationActions: { marginTop: spacing.md, paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.border, flexDirection: "row", gap: spacing.sm },
  progressGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  progressMetric: { width: "48%", minHeight: 112, borderRadius: radius.xl, padding: spacing.lg, justifyContent: "center", gap: spacing.xs },
  progressValue: { fontSize: 32, fontWeight: "900" },
  progressLabel: { color: colors.textSecondary, fontSize: 13, fontWeight: "700", lineHeight: 18 },
  classChips: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs, marginTop: spacing.md },
  classChip: { paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, borderRadius: radius.pill, backgroundColor: colors.primarySoft },
  classChipText: { color: colors.primary, fontSize: 12, fontWeight: "800" },
  managementActions: { marginTop: spacing.sm },
  managementRow: { minHeight: 64, flexDirection: "row", alignItems: "center", gap: spacing.sm, borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: spacing.sm },
  managementIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: colors.surfaceMuted, alignItems: "center", justifyContent: "center" },
  managementTitle: { color: colors.navy, fontSize: 14, fontWeight: "900" },
  managementMeta: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  quarantineAction: { minHeight: 42, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing.xs, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.danger, borderRadius: radius.lg, backgroundColor: colors.dangerBg },
  quarantineActionText: { color: colors.danger, fontSize: 13, fontWeight: "900" },
  modelRow: { flexDirection: "row", alignItems: "center", gap: spacing.md, borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: spacing.md, marginTop: spacing.sm },
  heroModelRow: { flexDirection: "row", alignItems: "center", gap: spacing.md, paddingVertical: spacing.md },
  heroModelVersion: { color: colors.navy, fontSize: 24, lineHeight: 29, fontWeight: "900", flexShrink: 1 },
  candidateRow: { flexDirection: "row", alignItems: "center", gap: spacing.md, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: spacing.md, marginTop: spacing.sm },
  modelIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.surfaceMuted, alignItems: "center", justifyContent: "center" },
  modelRole: { color: colors.textMuted, fontSize: 12, fontWeight: "800", letterSpacing: 0.7 },
  modelVersion: { color: colors.navy, fontSize: 14, fontWeight: "800", marginTop: 2 },
  lifecycleEmpty: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginTop: spacing.md, padding: spacing.md, borderRadius: radius.lg, backgroundColor: colors.surfaceMuted },
  lifecycleEmptyText: { flex: 1, color: colors.textMuted, fontSize: 13, lineHeight: 18 },
  selectionControls: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md, marginVertical: spacing.md },
  selectionAvailable: { color: colors.textSecondary, fontSize: 13, fontWeight: "800" },
  selectionControlButtons: { flexDirection: "row", gap: spacing.xs },
  selectionControl: { minHeight: 38, justifyContent: "center", paddingHorizontal: spacing.sm, borderRadius: radius.md, backgroundColor: colors.surfaceMuted },
  selectionControlText: { color: colors.primary, fontSize: 13, fontWeight: "900" },
  selectionControlDisabled: { color: colors.textMuted },
  trainingSelectionRowSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
  trainingSelectionTitle: { color: colors.navy, fontSize: 14, lineHeight: 19, fontWeight: "900" },
  metricHeader: { flexDirection: "row", alignItems: "center", paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border },
  metricRow: { flexDirection: "row", alignItems: "center", minHeight: 44, borderBottomWidth: 1, borderBottomColor: colors.border },
  metricName: { flex: 1.15, color: colors.textSecondary, fontSize: 12, fontWeight: "700" },
  metricNumber: { flex: 0.9, color: colors.navy, fontSize: 12, fontWeight: "800", textAlign: "right" },
  metricDelta: { flex: 0.9, color: colors.textMuted, fontSize: 12, fontWeight: "800", textAlign: "right" },
  positiveDelta: { color: colors.successFg },
  negativeDelta: { color: colors.danger },
  comparisonSection: { borderTopWidth: 1, borderTopColor: colors.border, marginTop: spacing.md, paddingTop: spacing.md },
  comparisonSectionTitle: { color: colors.navy, fontSize: 14, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.5 },
  comparisonSectionDescription: { color: colors.textMuted, fontSize: 12, lineHeight: 17, marginTop: spacing.xs },
  comparisonRoles: { flexDirection: "row", gap: spacing.lg, padding: spacing.md, borderRadius: radius.lg, backgroundColor: colors.surface },
  metricsUnavailable: { color: colors.textMuted, fontSize: 12, fontStyle: "italic", lineHeight: 17, marginTop: spacing.sm },
  productCapability: { gap: spacing.xs, marginTop: spacing.sm, padding: spacing.md, borderRadius: radius.lg, backgroundColor: colors.surface },
  productSupport: { color: colors.textSecondary, fontSize: 12, fontWeight: "700" },
  productUnsupported: { color: colors.textMuted, fontSize: 12, fontWeight: "700", marginTop: spacing.xs },
  productMetrics: { gap: spacing.xs, marginTop: spacing.xs },
  productMetricHeading: { color: colors.textSecondary, fontSize: 12, fontWeight: "800" },
  productMetricRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  productMetricLabel: { color: colors.textMuted, fontSize: 12 },
  productMetricValue: { color: colors.navy, fontSize: 12, fontWeight: "900" },
  classPreservationFailure: { flexDirection: "row", alignItems: "flex-start", gap: spacing.sm, padding: spacing.md, borderRadius: radius.lg, backgroundColor: colors.dangerBg },
  classPreservationTitle: { color: colors.danger, fontSize: 14, fontWeight: "900", textTransform: "uppercase" },
  classPreservationText: { color: colors.danger, fontSize: 12, lineHeight: 17, marginTop: 2 },
  promotionResult: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.sm },
  rollbackInformational: { color: colors.textMuted, fontSize: 12, lineHeight: 17, padding: spacing.sm, borderRadius: radius.md, backgroundColor: colors.surfaceMuted },
  readinessBox: { marginTop: spacing.sm, flexDirection: "row", alignItems: "flex-start", gap: spacing.sm, borderRadius: radius.lg, padding: spacing.md },
  readinessReady: { backgroundColor: colors.successBg },
  readinessBlocked: { backgroundColor: colors.warningBg },
  readinessReason: { color: colors.textSecondary, fontSize: 13, lineHeight: 18 },
  trainingHistory: { marginTop: spacing.md },
  trainingRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm, paddingVertical: spacing.md, borderTopWidth: 1, borderTopColor: colors.border },
  trainingMarker: { width: 34, height: 34, borderRadius: 12, backgroundColor: colors.surfaceMuted, alignItems: "center", justifyContent: "center" },
  trainingModel: { color: colors.navy, fontSize: 13, fontWeight: "800" },
  trainingMeta: { color: colors.textMuted, fontSize: 12, marginTop: 3 },
  lifecycleActions: { gap: spacing.sm, marginTop: spacing.lg },
  actionHint: { color: colors.textMuted, fontSize: 12, lineHeight: 17, marginTop: spacing.sm },
  jobStatus: { flexDirection: "row", alignItems: "center", gap: spacing.md, backgroundColor: colors.primarySoft, borderRadius: radius.lg, padding: spacing.md, marginTop: spacing.md },
  jobTitle: { color: colors.navy, fontWeight: "800", fontSize: 13 },
  jobMeta: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  rollbackSection: { borderTopWidth: 1, borderTopColor: colors.border, marginTop: spacing.lg, paddingTop: spacing.md },
  rollbackRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginTop: spacing.md },
  rollbackChoice: { gap: spacing.sm, padding: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, backgroundColor: colors.surface },
  rollbackChoiceSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
  rollbackChoiceMain: { flexDirection: "row", alignItems: "center", gap: spacing.sm, minHeight: 48 },
  rollbackFooter: { flexDirection: "row", gap: spacing.sm },
  rollbackComparisonModels: { flexDirection: "row", gap: spacing.lg, padding: spacing.md, borderRadius: radius.lg, backgroundColor: colors.surfaceMuted },
  actionBreakdown: { marginTop: spacing.lg, gap: spacing.xs },
  actionRow: { minHeight: 66, flexDirection: "row", alignItems: "center", gap: spacing.md, borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: spacing.sm },
  actionIcon: { width: 40, height: 40, borderRadius: 13, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" },
  actionLabel: { color: colors.navy, fontWeight: "800", fontSize: 14 },
  actionDescription: { color: colors.textMuted, fontSize: 12 },
  actionCount: { minWidth: 36, color: colors.primary, fontWeight: "900", fontSize: 24, textAlign: "right" },
  progressNote: { flexDirection: "row", gap: spacing.sm, backgroundColor: colors.infoBg, borderRadius: radius.lg, padding: spacing.md },
  successBox: { flexDirection: "row", alignItems: "center", gap: spacing.sm, backgroundColor: colors.successBg, borderRadius: radius.lg, padding: spacing.md },
  successText: { flex: 1, color: colors.successFg, fontWeight: "700", lineHeight: 19 },
  successLink: { color: colors.successFg, fontWeight: "900", marginTop: spacing.xs, textDecorationLine: "underline" },
  sheetBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(15, 23, 42, 0.55)" },
  sheet: { maxHeight: "94%", minHeight: "42%", gap: spacing.md, padding: spacing.lg, paddingBottom: spacing.xl, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, backgroundColor: colors.surface },
  sheetScroll: { flexGrow: 0 },
  sheetContent: { gap: spacing.sm, paddingBottom: spacing.md },
  sheetHelper: { color: colors.textMuted, fontSize: 12, lineHeight: 17 },
  sheetQuarantineLink: { minHeight: 42, flexDirection: "row", alignItems: "center", gap: spacing.xs, paddingHorizontal: spacing.sm, borderRadius: radius.md, backgroundColor: colors.dangerBg },
  sheetQuarantineText: { flex: 1, color: colors.danger, fontSize: 13, fontWeight: "900" },
  trainingGroup: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, overflow: "hidden" },
  trainingGroupRow: { minHeight: 62, flexDirection: "row", alignItems: "center", gap: spacing.sm, padding: spacing.md, backgroundColor: colors.surface },
  trainingGroupOpen: { flex: 1, flexDirection: "row", alignItems: "center", gap: spacing.sm },
  trainingGroupTitle: { color: colors.navy, fontSize: 15, fontWeight: "900" },
  trainingGroupMeta: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  trainingDrilldown: { gap: spacing.sm, padding: spacing.sm, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.surfaceMuted },
  trainingSubmissionDetail: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, overflow: "hidden", backgroundColor: colors.surface },
  trainingSubmissionRow: { minHeight: 56, flexDirection: "row", alignItems: "center", gap: spacing.sm, padding: spacing.sm },
  trainingThumbnail: { width: 72, maxHeight: 72, borderRadius: radius.md, backgroundColor: colors.border },
  wholeSubmissionNote: { color: colors.primary, fontSize: 11, fontWeight: "800", marginTop: 3 },
  quarantineCard: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, overflow: "hidden" },
  quarantineRow: { minHeight: 64, flexDirection: "row", alignItems: "center", gap: spacing.sm, padding: spacing.md, backgroundColor: colors.surface },
  quarantineDetails: { gap: spacing.sm, padding: spacing.md, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.surfaceMuted },
  annotationSubmissionPreview: { width: "100%", gap: spacing.sm },
  quarantineImage: { width: "100%", maxHeight: 260, borderRadius: radius.lg, backgroundColor: colors.border },
  quarantineAnnotation: { padding: spacing.sm, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 2, borderColor: "transparent" },
  quarantineAnnotationFocused: { borderColor: colors.amber },
  quarantineAnnotationHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm },
  quarantineBoxNotice: { color: colors.textMuted, fontSize: 12, fontWeight: "700" },
  archiveToggleRow: { minHeight: 52, flexDirection: "row", alignItems: "center", gap: spacing.md, paddingHorizontal: spacing.sm, borderRadius: radius.lg, backgroundColor: colors.surfaceMuted },
  archiveToggleHint: { color: colors.textMuted, fontSize: 11, lineHeight: 16, marginTop: 2 },
  modelCardHeader: { flexDirection: "row", alignItems: "flex-start", gap: spacing.md },
  modelDisplayName: { color: colors.navy, fontSize: 20, lineHeight: 25, fontWeight: "900" },
  modelVersionCompact: { color: colors.textMuted, fontSize: 12, lineHeight: 17, fontWeight: "700" },
  compactDivider: { height: 1, backgroundColor: colors.border, marginVertical: spacing.md },
  candidateCompactRow: { flexDirection: "row", alignItems: "center", gap: spacing.md },
  comparisonCompact: { marginTop: spacing.md, padding: spacing.md, borderRadius: radius.lg, backgroundColor: colors.surfaceMuted, gap: spacing.sm },
  comparisonCompactHeader: { flexDirection: "row", alignItems: "flex-start", gap: spacing.sm },
  comparisonCompactTitle: { color: colors.navy, fontSize: 15, fontWeight: "900" },
  comparisonCompactText: { color: colors.textMuted, fontSize: 12, lineHeight: 17 },
  metricSummaryRow: { flexDirection: "row", gap: spacing.xs },
  metricSummaryItem: { flex: 1, padding: spacing.sm, borderRadius: radius.md, backgroundColor: colors.surface },
  metricSummaryLabel: { color: colors.textMuted, fontSize: 9, lineHeight: 12, fontWeight: "800" },
  metricSummaryValue: { color: colors.navy, fontSize: 15, fontWeight: "900", marginTop: 3 },
  comparisonDetailsToggle: { minHeight: 38, flexDirection: "row", alignItems: "center", alignSelf: "flex-start", gap: spacing.xs },
  comparisonDetailsText: { color: colors.primary, fontSize: 12, fontWeight: "900" },
  comparisonDetails: { gap: spacing.sm },
  primaryLifecycleAction: { gap: spacing.xs },
  systemDecision: { minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing.sm, borderRadius: radius.lg, backgroundColor: colors.primarySoft },
  systemDecisionText: { color: colors.textSecondary, fontSize: 13, fontWeight: "800" },
  quickActions: { flexDirection: "row", gap: spacing.sm },
  quickAction: { flex: 1, minHeight: 74, flexDirection: "row", alignItems: "center", gap: spacing.sm, padding: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, backgroundColor: colors.surface },
  quickActionDanger: { borderColor: colors.danger, backgroundColor: colors.dangerBg },
  quickActionIcon: { width: 34, height: 34, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: colors.primarySoft },
  quickActionIconDanger: { backgroundColor: colors.dangerBg },
  quickActionTitle: { color: colors.navy, fontSize: 13, fontWeight: "900" },
  quickActionTitleDanger: { color: colors.danger },
  quickActionMeta: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  trainingSubmissionOpen: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: spacing.sm },
  quarantineGroupRow: { minHeight: 62, flexDirection: "row", alignItems: "center", gap: spacing.sm, padding: spacing.md, backgroundColor: colors.surface },
  quarantineGroupIcon: { width: 34, height: 34, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: colors.dangerBg },
  quarantineSubmission: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, overflow: "hidden", backgroundColor: colors.surface },
  quarantineSubmissionArchived: { opacity: 0.82, backgroundColor: colors.surfaceMuted },
  quarantineSubmissionRow: { minHeight: 56, flexDirection: "row", alignItems: "center", gap: spacing.sm, padding: spacing.sm },
  quarantineSubmissionTitleRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: spacing.xs },
  imageBackdrop: { flex: 1, backgroundColor: "rgba(15, 23, 42, 0.72)", alignItems: "center", justifyContent: "center", padding: spacing.lg },
  imageModal: { width: "100%", maxWidth: 520, backgroundColor: colors.surface, borderRadius: radius.xl, padding: spacing.lg, gap: spacing.md },
  imageHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  imageTitle: { ...typography.section, color: colors.navy },
  imageSubtitle: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  scanImage: { width: "100%", height: 430, backgroundColor: colors.surfaceMuted, borderRadius: radius.lg },
  imageNote: { color: colors.textMuted, fontSize: 12, textAlign: "center" },
  labelModal: { width: "100%", maxWidth: 460, backgroundColor: colors.surface, borderRadius: radius.xl, padding: spacing.lg, gap: spacing.md },
  boxEditorModal: { width: "100%", maxWidth: 560, backgroundColor: colors.surface, borderRadius: radius.xl, padding: spacing.md, gap: spacing.md },
  boxEditorScreen: { flex: 1, backgroundColor: colors.background },
  boxEditorScreenContent: { flex: 1, padding: spacing.lg, paddingTop: spacing.xl, gap: spacing.md },
  boxEditorActions: { flexDirection: "row", gap: spacing.sm },
  inputLabel: { color: colors.textSecondary, fontWeight: "700", fontSize: 13 },
  modalError: { color: colors.danger, backgroundColor: colors.dangerBg, borderRadius: radius.md, padding: spacing.sm, fontWeight: "600" },
  modalActions: { gap: spacing.sm },
  confirmIcon: { width: 58, height: 58, borderRadius: 29, backgroundColor: colors.dangerBg, alignItems: "center", justifyContent: "center", alignSelf: "center" },
  confirmSuccessIcon: { width: 58, height: 58, borderRadius: 29, backgroundColor: colors.successBg, alignItems: "center", justifyContent: "center", alignSelf: "center" },
  confirmTitle: { ...typography.section, color: colors.navy, textAlign: "center" },
  confirmMessage: { ...typography.body, color: colors.textMuted, lineHeight: 22, textAlign: "center" },
  confirmLabel: { color: colors.navy, fontWeight: "800" },
});
